[2024-11-01T19:23:45.760+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-01T19:23:45.782+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: read_kafka.read_from_kafka manual__2024-11-01T19:23:43.166360+00:00 [queued]>
[2024-11-01T19:23:45.794+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: read_kafka.read_from_kafka manual__2024-11-01T19:23:43.166360+00:00 [queued]>
[2024-11-01T19:23:45.795+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-11-01T19:23:45.820+0000] {taskinstance.py:2888} INFO - Executing <Task(ConsumeFromTopicOperator): read_from_kafka> on 2024-11-01 19:23:43.166360+00:00
[2024-11-01T19:23:45.827+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=200) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-01T19:23:45.829+0000] {standard_task_runner.py:72} INFO - Started process 201 to run task
[2024-11-01T19:23:45.829+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'read_kafka', 'read_from_kafka', 'manual__2024-11-01T19:23:43.166360+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/read_kafka.py', '--cfg-path', '/tmp/tmpzr893ise']
[2024-11-01T19:23:45.830+0000] {standard_task_runner.py:105} INFO - Job 8: Subtask read_from_kafka
[2024-11-01T19:23:45.892+0000] {task_command.py:467} INFO - Running <TaskInstance: read_kafka.read_from_kafka manual__2024-11-01T19:23:43.166360+00:00 [running]> on host 1571d3dd6210
[2024-11-01T19:23:45.997+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='read_kafka' AIRFLOW_CTX_TASK_ID='read_from_kafka' AIRFLOW_CTX_EXECUTION_DATE='2024-11-01T19:23:43.166360+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-01T19:23:43.166360+00:00'
[2024-11-01T19:23:45.998+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-01T19:23:46.027+0000] {base.py:84} INFO - Retrieving connection 'donki-cme-broker'
[2024-11-01T19:24:46.032+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/kafka/operators/consume.py", line 175, in execute
    apply_callable(msgs)
  File "/opt/airflow/dags/read_kafka.py", line 66, in consumer_function
    key = json.loads(message.key())
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)
[2024-11-01T19:24:46.052+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=read_kafka, task_id=read_from_kafka, run_id=manual__2024-11-01T19:23:43.166360+00:00, execution_date=20241101T192343, start_date=20241101T192345, end_date=20241101T192446
[2024-11-01T19:24:46.073+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-01T19:24:46.074+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 8 for task read_from_kafka (Extra data: line 1 column 5 (char 4); 201)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/kafka/operators/consume.py", line 175, in execute
    apply_callable(msgs)
  File "/opt/airflow/dags/read_kafka.py", line 66, in consumer_function
    key = json.loads(message.key())
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)
[2024-11-01T19:24:46.101+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-01T19:24:46.119+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-01T19:24:46.122+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
