[2024-10-31T17:20:29.466+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-31T17:20:29.490+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: write_kafka.write_to_kafka manual__2024-10-31T17:20:27.402654+00:00 [queued]>
[2024-10-31T17:20:29.503+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: write_kafka.write_to_kafka manual__2024-10-31T17:20:27.402654+00:00 [queued]>
[2024-10-31T17:20:29.504+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-31T17:20:29.554+0000] {taskinstance.py:2888} INFO - Executing <Task(ProduceToTopicOperator): write_to_kafka> on 2024-10-31 17:20:27.402654+00:00
[2024-10-31T17:20:29.564+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3072) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-31T17:20:29.566+0000] {standard_task_runner.py:72} INFO - Started process 3077 to run task
[2024-10-31T17:20:29.567+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'write_kafka', 'write_to_kafka', 'manual__2024-10-31T17:20:27.402654+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/write_kafka.py', '--cfg-path', '/tmp/tmp_ilc53gl']
[2024-10-31T17:20:29.570+0000] {standard_task_runner.py:105} INFO - Job 10: Subtask write_to_kafka
[2024-10-31T17:20:29.642+0000] {task_command.py:467} INFO - Running <TaskInstance: write_kafka.write_to_kafka manual__2024-10-31T17:20:27.402654+00:00 [running]> on host beba2d03a603
[2024-10-31T17:20:30.212+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='write_kafka' AIRFLOW_CTX_TASK_ID='write_to_kafka' AIRFLOW_CTX_EXECUTION_DATE='2024-10-31T17:20:27.402654+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-31T17:20:27.402654+00:00'
[2024-10-31T17:20:30.214+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-31T17:20:30.230+0000] {base.py:84} INFO - Retrieving connection 't1-3'
[2024-10-31T17:20:30.273+0000] {produce.py:41} INFO - Producer <cimpl.Producer object at 0x7f5a40861da0>
[2024-10-31T17:20:30.276+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/kafka/operators/produce.py", line 125, in execute
    for k, v in producer_callable():
                ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom_arg.py", line 329, in __iter__
    raise TypeError("'XComArg' object is not iterable")
TypeError: 'XComArg' object is not iterable
[2024-10-31T17:20:30.298+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=write_kafka, task_id=write_to_kafka, run_id=manual__2024-10-31T17:20:27.402654+00:00, execution_date=20241031T172027, start_date=20241031T172029, end_date=20241031T172030
[2024-10-31T17:20:30.328+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-31T17:20:30.330+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 10 for task write_to_kafka ('XComArg' object is not iterable; 3077)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/kafka/operators/produce.py", line 125, in execute
    for k, v in producer_callable():
                ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom_arg.py", line 329, in __iter__
    raise TypeError("'XComArg' object is not iterable")
TypeError: 'XComArg' object is not iterable
[2024-10-31T17:20:30.386+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-31T17:20:30.408+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-31T17:20:30.420+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
